### PR TITLE
fix: limit job name width and details 

### LINKED ISSUE #4: Add a text-limit to the name column for long non-breaking job names
In the Taskless Dev Server, the `name` column of the data table doesn't have a maximum width (see attached for how the column pushes beyond the page bounds).

Some possible fixes:

- The column could be capped at a reasonable character length with an ellipsis based overflow, using a `title` attribute. This would result in a very compact data table at the expense of readability
- On display, a `<wbr/>` could be injected after every non `a-z0-9`, letting long names wrap at the browser's discretion. This would let developers see the full job's name, but would make horizontal scanning more difficult
- Your own ideas for how to improve the DataTable component's layout

image

### PR DESCRIPTION
**Pull request by TAKANOME-DEV**
- Add max width of `300px` for `DEFAULT_CELL` width and `text-ellipsis` to the job name

| after_jobs 	| before_jobs 	|
|----------------------------------------------------------------------------------------------------------------------	|-----------------------------------------------------------------------------------------------------------------------	|
|                                                                                                                      	|                                                                                                                       	|

- Add `overflow-hidden` to the logs table container and `max-w-5xl` for the job details

|logs_before	| logs_after	|
|----------------------------------------------------------------------------------------------------------------------	|-----------------------------------------------------------------------------------------------------------------------	|
|                                                                                                                      	|                                                                                                                       	|

Fixes #4

### CODE REVIEW

File: packages/ui/src/components/DataTable.tsx [hunk 1]
```diff
@@ -34,7 +34,7 @@ type TableValue = Record<string | number | symbol, unknown>;
 
 const DEFAULT_HEAD =
   "py-3.5 px-3 text-left text-sm font-semibold text-gray-900";
-const DEFAULT_CELL = "py-4 px-3 text-sm text-gray-500";
+const DEFAULT_CELL = "py-4 px-3 text-sm text-gray-500 max-w-[300px]";
```
Comment (jakobo) [inline packages/ui/src/components/DataTable.tsx:37]: May want to consider mobile screen sizes, plus either a width of 72 or 80 (https://tailwindcss.com/docs/width): `max-w-full md:max-w-72`. This avoids having too many custom values that need checking in a design change.

File: packages/dev/src/pages/index.tsx [hunk 2]
```diff
@@ -176,12 +176,12 @@ const Home: NextPage = () => {
   return (
     <Layout title="Jobs - Taskless Development Server">
       <div className="flex flex-row gap-3 pb-3">
-        <div className="w-full relative flex flex-row">{/* Search */}</div>
+        <div className="relative flex flex-row w-full">{/* Search */}</div>
         <button
-          className="flex-shrink-0 bg-primary-700 text-white px-3 py-2 rounded-md flex flex-row items-center gap-3 hover:bg-primary-500 transition"
+          className="flex flex-row items-center flex-shrink-0 gap-3 px-3 py-2 text-white transition rounded-md bg-primary-700 hover:bg-primary-500"
```
Comment (jakobo) [inline packages/dev/src/pages/index.tsx:181]: Is there a plugin / code formatter that's updating the order of classes? I see [there is an official plugin for prettier](https://tailwindcss.com/blog/automatic-class-sorting-with-prettier), but we don't have that added yet in our own package.json.

Specifically asking because the reordering does make it difficult to tell which changes are specific to this PR vs formatting improvements.

**Review by jakobo — CHANGES_REQUESTED** [review]
Just a few comments RE formatting and supporting mobile screen sizes. Thank you for putting this together! :heart:

File: packages/dev/src/pages/index.tsx (hunk 2 above)
Comment (TAKANOME-DEV) [reply packages/dev/src/pages/index.tsx:181]: Sorry about that :sweat: it's an extension, I will revert it :+1:

File: packages/ui/src/components/DataTable.tsx (hunk 1 above)
Comment (TAKANOME-DEV) [reply packages/ui/src/components/DataTable.tsx:37]: sure

Comment (TAKANOME-DEV) [reply packages/ui/src/components/DataTable.tsx:37]: it does not work with `max-w-72 or max-w-80`, and for the logs when the details are opened, it overflows.
Will take more time to fix it :v:

File: packages/dev/src/pages/index.tsx (hunk 2 above)
Comment (jakobo) [reply packages/dev/src/pages/index.tsx:181]: No worries! I actually think this is a good thing. Let me put the plugin in place across the board, as it will make diffing the changes much easier.

**Comment by TAKANOME-DEV** [comment]
Added a `div` container to eliminate horizontal scrolling :arrow_down: 

[taskless.webm](https://user-images.githubusercontent.com/79809121/194915505-db7b25d4-2b99-4628-b272-fb35c39d129d.webm)

File: packages/dev/src/pages/logs.tsx [hunk 3]
```diff
@@ -84,6 +84,7 @@ const Logs: NextPage = () => {
             let payload: TaskData | undefined;
             try {
               payload = JSON.parse(record.payload);
+              console.log({ payload });
```
Comment (jakobo) [inline packages/dev/src/pages/logs.tsx:87]: Do we need this console.log statement?

**Review by jakobo — COMMENTED** [review]
Looks good. Only one small question in the review RE a console.log statement. 🚀

File: packages/dev/src/pages/logs.tsx (hunk 3 above)
Comment (TAKANOME-DEV) [reply packages/dev/src/pages/logs.tsx:87]: My bad, just have a habit to throw console.log everywhere :sweat_smile: , gonna remove it

**Review by jakobo — APPROVED** [review]

**Comment by jakobo** [comment]
@all-contributors please add @TAKANOME-DEV for code ❤️
